apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader
  labels:
    app: reader
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - name: reader
        image: sgorawski/reader:latest
        ports:
        - containerPort: 80
        env:
        - name: DBNAME
          value: db
        - name: USER
          value: postgres
        - name: PASSWORD
          value: postgres
        - name: HOST
          value: "35.242.213.248"
        - name: PORT
          value: "5432"
