apiVersion: v1
kind: Service
metadata:
  name: broker-service
spec:
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: messaging
  - port: 8080
    targetPort: 15672
    protocol: TCP
    name: management
  selector:
    app: broker
  type: ClusterIP

